name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v4

      - name: Vérifier le fichier ZIP
        run: |
          ls -la
